export enum ToastMessage {
  TASK_CREATED_SUCCESSFULLY = "TASK_CREATED_SUCCESSFULLY",
  TASK_DELETED_SUCCESSFULLY = "TASK_DELETED_SUCCESSFULLY",
  TASK_COMPLETED_SUCCESSFULLY = "TASK_COMPLETED_SUCCESSFULLY"
}